In [134]:
import numpy as np

In [21]:
#3.1 --- 1D Numpy Arrays ---
list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]
arr=np.array(list)
print(arr*4)
print(np.mean(list))
print(np.median(list))
print(np.std(list))
print("index of smallest number =", (np.argmin(arr)))
print("index of biggest number =", (np.argmax(arr)))
print("smallest number =", arr[6])
print("biggest number =", arr[7])
print("min =", np.min(arr))
print("max =", np.max(arr)) #values for min and max match
mask = arr>20
arr_bigger20 = arr[mask]
print(f'{arr_bigger20}')

[ 80 108  36  48 124  68  16 200 156 140]
24.4
23.5
13.828955130450023
index of smallest number = 6
index of biggest number = 7
smallest number = 4
biggest number = 50
min = 4
max = 50
[27 31 50 39 35]


In [63]:
#3.2 --- 2D Numpy Arrays ---
matrix = [
    [5, 12, 17, 9],
    [8, 21, 14, 3],
    [6, 13, 19, 11]
]
arrmatrix = np.array(matrix)
print(np.shape(matrix))  # 3 rows, 4 columns
print(arrmatrix[:,2])
print(arrmatrix[1,:])
print(arrmatrix*2)
print(np.mean(arrmatrix, axis = 0))
print(np.mean(arrmatrix))
print("max value row =", np.max(arrmatrix, axis=1))
print("min value column =", np.min(arrmatrix, axis=0))
newmatrix=arrmatrix.flatten()
print(newmatrix)
print("shape of flattened matrix =", np.shape(newmatrix))
#all 12 items were moved to one row, but the 12 is written as the first # in given tuple
print("index of min =", np.argmin(newmatrix))
print("index of max =", np.argmax(newmatrix))
print(np.unravel_index(7, (3, 4)))
print(np.unravel_index(5, (3, 4)))
mask = arrmatrix>15
arrmatrix_15up = arrmatrix[mask]
print("matrix greater than 15 =", arrmatrix_15up)
print("sorted arrmatrix_15up =", np.sort(arrmatrix_15up))

(3, 4)
[17 14 19]
[ 8 21 14  3]
[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]
[ 6.33333333 15.33333333 16.66666667  7.66666667]
11.5
max value row = [17 21 19]
min value column = [ 5 12 14  3]
[ 5 12 17  9  8 21 14  3  6 13 19 11]
shape of flattened matrix = (12,)
index of min = 7
index of max = 5
(np.int64(1), np.int64(3))
(np.int64(1), np.int64(1))
matrix greater than 15 = [17 21 19]
sorted arrmatrix_15up = [17 19 21]


In [77]:
#4 --- Prime Star Systems ---
arr = np.array([
    [2, 3, 5],
    [14, 6, 8],
    [11, 13, 17],
    [7, 10, 13]
])
def primeinrow(list):
    def prime_number(n):
        if n<2:
            return False
        for i in range(2, int(n**0.5)+1):  #+1 since last value is exclusive
            if n%i == 0:
                return False
            else:
                return True
    for a in list:
        if prime_number(a):
            return True

def find_rows_prime(arr):
    rows_prime = []
    for row in arr:
        if primeinrow(row):
            rows_prime.append(row)
    return(print(rows_prime))
find_rows_prime(arr)
    

[array([2, 3, 5]), array([11, 13, 17]), array([ 7, 10, 13])]


In [106]:
#5 --- Let's Play Checkers ---
#5.1
def zero_checkerboard():
    print(np.zeros((8,8)))
zero_checkerboard()
#5.2 and 5.3 --- Checkerboard
arr=np.zeros((8,8))
for i in range(arr.shape[0]):  #rows index
    for j in range(arr.shape[1]):  #columns index
        if (i+j) %2 ==0:
            arr[i][j] = 1
print(arr)

#5.4 --- Reverse Checkerboard
arr2=np.zeros((8,8))
for i in range(arr2.shape[0]):  #rows index
    for j in range(arr2.shape[1]):  #columns index
        if (i+j) %2 !=0:
            arr2[i][j] = 1
print(arr2)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [151]:
#6 --- The Expanding Universe ---
# universe = np.array(['galaxy', 'clusters'])

# def expansion(list[universe], x):
#     for c in list[universe]:
#         universe.join(c+" "*x)
# print(expansion(unviverse, 2))

# from builtins import list
# def expand(str,n):
#     strlist=list(str)
#     expandedlist=[]
#     for i in range(len(strlist)):
#         expandedlist.append(strlist[i])
#         if i < len(strlist)-1:
#             for j in range(n):
#                 expandedlist.append(" ")
#     expandedlist="".join(expandedlist)
#     return expandedlist

def expanding(word,n):
    word_listed=list(word)
    expand_list=[]
    for i in range(len(word_listed)):
        expand_list.append(word_listed[i])
        if i < len(word_listed)-1:
            for j in range(n):
                expand_list.append(" ")
    expand_list="".join(expand_list)
    return expand_list
expanding(word="hello", n=3)

'h   e   l   l   o'

In [139]:
#7 --- Second-Brightest Star ---
np.random.seed(123)
stars=np.random.randint(500, 2000, (5,5))
print(stars)

def second_brightest_star(stars):
    second_brightest_numbers = []
    for row in stars:
        sorted_row = np.sort(row)
        second_brightest_numbers.append(sorted_row[3])
    return(print(second_brightest_numbers))
second_brightest_star(stars)

[[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]
[np.int32(1889), np.int32(1647), np.int32(1138), np.int32(1863), np.int32(1592)]
